version: '3.9'

services:
  db:
    image: postgres:15
    container_name: local-postgres
    restart: always
    ports:
      - "5432:5432" # Expose PostgreSQL on localhost:5432
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data:
